name: LiipImagineBundle CI

on: push

jobs:
  phpunit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          extensions: imagick
          ini-values: disable_functions=imagewebp

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Update project dependencies
        run: composer update --no-interaction --no-progress --ansi

      - name: Cache PHPUnit
        uses: actions/cache@v2
        with:
          path: vendor/bin/.phpunit
          key: ${{ runner.os }}-phpunit

      - name: Run PHPUnit tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: max[self]=0
        run: vendor/bin/simple-phpunit -v
